global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['192.168.11.101:9323']
      - targets: ['192.168.11.102:9323']

  - job_name: 'application1'
    static_configs:
      - targets: ['192.168.11.101:8081']
      - targets: ['192.168.11.101:8082']

  - job_name: 'application2'
    static_configs:
      - targets: ['192.168.11.102:8081']
      - targets: ['192.168.11.102:8082']
      - targets: ['192.168.11.102:8083']